<build>
    <sourceDirectory>${project.basedir}/dev</sourceDirectory>
    <testSourceDirectory>${project.basedir}/dev/tests</testSourceDirectory>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.13.0</version>
            <configuration>
                <excludes>
                    <exclude>tests/**</exclude>
                </excludes>
            </configuration>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>3.0.0</version>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jar-plugin</artifactId>
            <version>3.3.0</version>
            <configuration>
                <archive>
                    <manifest>
                        <mainClass>presentation.Main</mainClass>
                        <addClasspath>true</addClasspath>
                    </manifest>
                </archive>
                <outputDirectory>${project.basedir}/release</outputDirectory>
                <finalName>adss2025_v01</finalName>
            </configuration>
        </plugin>
    </plugins>
</build>